# Generated by Django 5.1.7 on 2025-03-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyreScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
